AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  FullDomainName:
    AllowedPattern: "[a-z0-9]+[-.a-z0-9]*(\\.[a-z][a-z]+)+"
    ConstraintDescription: "Provide a valid domain name using only lowercase letters, numbers, and dash (-)"
    Description: The full domain name.
    Type: String
  HostedZoneId:
    ConstraintDescription: must be a valid service ID
    Description: The ID of the hosted zone.
    Type: String
  ServiceDomainName:
    AllowedPattern: "(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)"
    ConstraintDescription: "Must be a valid DNS domain name."
    Description: The domain name of the CloudFront distribution.
    Type: String

Resources:
  DnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      RecordSets:
      - Name: !Sub '${FullDomainName}.'
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 #This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution
          DNSName: !Ref 'ServiceDomainName'

Outputs:
  DnsRecord:
    Description: The dns record ID
    Value: !Ref 'DnsRecord'