template_path: route53/dnsalias.yaml

parameters:
  FullDomainName: {{ full_domain_name }}
  HostedZoneId: {{ hosted_zone_id }}
  ServiceDomainName: !stack_output access/cloudfront.yaml::ServiceDomainName

stack_tags:
  Project: {{ project_code }}